# Generated by Django 6.0.3 on 2026-04-15 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='attendance_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='next_term_begins',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='number_on_roll',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='position_in_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='promoted_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='times_absent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='times_present',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='times_school_opened',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='vacation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReportCardTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_type', models.CharField(choices=[('psychomotor', 'Psychomotor'), ('affective', 'Affective')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('rating', models.CharField(blank=True, max_length=20, null=True)),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='academics.reportcard')),
            ],
            options={
                'ordering': ['trait_type', 'name'],
                'unique_together': {('report_card', 'trait_type', 'name')},
            },
        ),
    ]
