# Generated by Django 6.0.3 on 2026-04-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_reportcard_attendance_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultpin',
            name='max_usage',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='resultpin',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
