# Generated by Django 6.0.3 on 2026-04-16 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_resultpin_max_usage_resultpin_usage_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultpin',
            name='is_used',
        ),
    ]
