# Generated by Django 6.0.3 on 2026-04-09 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_setting'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='teacher_profiles', to='core.branch'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='teacher_profiles', to='core.section'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_teacher_branch_profiles', to='core.branch'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_teacher_section_profiles', to='core.section'),
        ),
    ]
