"""Academic app URL configuration."""
from django.urls import path
from .views import (
    StudentResultsView,
    StudentReportCardsView,
    StudentNotesView,
    TeacherAssignmentsView,
    VerifyResultPinView,
    TeacherNoteUploadView,
    TeacherAssignmentStudentsView,
    TeacherResultUploadView,
    TeacherClassTeacherAssignmentsView,
    TeacherClassTeacherAssignmentStudentsView,
    TeacherUpdateClassTeacherRemarkView,
    TeacherReportCardTraitsView,
    TeacherUpdateReportCardTraitsView,
    TermListView,
    AdminResultPinListCreateView,
    AdminSubjectListView,
    AdminSubjectCreateView,
    AdminSubjectUpdateView,
    AdminAssignmentListView,
    AdminAssignmentCreateView,
    AdminAssignmentUpdateView,
    AdminClassSubjectListView,
    AdminManagedClassSubjectListView,
    AdminClassSubjectCreateView,
    AdminClassSubjectUpdateView,
    AdminReportCardsView,
    AdminClassTeacherAssignmentListCreateView,
    AdminClassTeacherAssignmentUpdateDeleteView,
    AdminUpdateHeadTeacherRemarkView,
    StudentReportCardTraitsView,
    StudentReportCardHTMLView,
    StudentReportCardPDFView,
)

urlpatterns = [
    path("student/results/", StudentResultsView.as_view(), name="student-results"),
    path("student/report-cards/", StudentReportCardsView.as_view(), name="student-report-cards"),
    path("student/notes/", StudentNotesView.as_view(), name="student-notes"),
    path("teacher/assignments/", TeacherAssignmentsView.as_view(), name="teacher-assignments"),
    path("teacher/notes/upload/", TeacherNoteUploadView.as_view(), name="teacher-note-upload"),
    path("teacher/assignment-students/", TeacherAssignmentStudentsView.as_view(), name="teacher-assignment-students"),
    path("teacher/class-teacher-assignments/", TeacherClassTeacherAssignmentsView.as_view(), name="teacher-class-teacher-assignments",),
    path("teacher/class-teacher-assignments/<int:assignment_id>/students/", TeacherClassTeacherAssignmentStudentsView.as_view(), name="teacher-class-teacher-assignment-students",),
    path("teacher/report-cards/<int:report_card_id>/class-teacher-remark/", TeacherUpdateClassTeacherRemarkView.as_view(), name="teacher-update-class-teacher-remark",),
    path("teacher/results/upload/", TeacherResultUploadView.as_view(), name="teacher-result-upload"),
    path("teacher/report-cards/<int:report_card_id>/traits/", TeacherReportCardTraitsView.as_view(), name="teacher-report-card-traits",),
    path("teacher/report-cards/<int:report_card_id>/traits/update/", TeacherUpdateReportCardTraitsView.as_view(), name="teacher-update-report-card-traits",),
    path("terms/", TermListView.as_view(), name="term-list"),
    path("student/verify-pin/", VerifyResultPinView.as_view(), name="verify-result-pin"),
    path("admin/result-pins/", AdminResultPinListCreateView.as_view(), name="admin-result-pins"),

    path("admin/subjects/", AdminSubjectListView.as_view(), name="admin-subjects"),
    path("admin/subjects/create/", AdminSubjectCreateView.as_view(), name="admin-create-subject"),
    path("admin/subjects/<int:subject_id>/update/", AdminSubjectUpdateView.as_view(), name="admin-update-subject"),
    path("admin/class-subjects/manage/", AdminManagedClassSubjectListView.as_view(), name="admin-manage-class-subjects"),
    path("admin/class-subjects/create/", AdminClassSubjectCreateView.as_view(), name="admin-create-class-subject"),
    path("admin/class-subjects/<int:class_subject_id>/update/", AdminClassSubjectUpdateView.as_view(), name="admin-update-class-subject"),
    path("admin/report-cards/", AdminReportCardsView.as_view(), name="admin-report-cards",),

    path("admin/assignments/", AdminAssignmentListView.as_view(), name="admin-assignments"),
    path("admin/assignments/create/", AdminAssignmentCreateView.as_view(), name="admin-create-assignment"),
    path("admin/assignments/<int:assignment_id>/update/", AdminAssignmentUpdateView.as_view(), name="admin-update-assignment"),
    path("admin/class-subjects/", AdminClassSubjectListView.as_view(), name="admin-class-subjects"),
    path("admin/class-teacher-assignments/", AdminClassTeacherAssignmentListCreateView.as_view(), name="admin-class-teacher-assignment-list-create",),
    path("admin/class-teacher-assignments/<int:assignment_id>/", AdminClassTeacherAssignmentUpdateDeleteView.as_view(), name="admin-class-teacher-assignment-update-delete",),
    path("admin/report-cards/<int:report_card_id>/head-teacher-remark/", AdminUpdateHeadTeacherRemarkView.as_view(), name="admin-update-head-teacher-remark",),

    path("student/report-cards/<int:report_card_id>/traits/", StudentReportCardTraitsView.as_view(), name="student-report-card-traits"),
    path("student/report-card/html/", StudentReportCardHTMLView.as_view(), name="student-report-card-html"),
    path("student/report-card/pdf/", StudentReportCardPDFView.as_view(), name="student-report-card-pdf"),
    path("student/report-card/pdf/<int:report_card_id>/", StudentReportCardPDFView.as_view(), name="student-report-card-pdf-by-id"),
]